typography_spectrum: 0.47176541946828365
color:
  brandStrength: 0.4736523702740669
  lightness: 0.1362778665497899
  saturation: 0.19101816508919
  rhythmicContrast: 0.9391752472147346
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.942954286467284
author:
  name: Ville Johannes Pajala
  email: valoraami@gmail.com
  url: www.villepajala.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7fb35733-dd01-4516-b3d1-2eb57e5c2d1d.jpg
name: Ville Johannes Pajala
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/45db0fc3-633b-4efc-8cbe-229c40180eda.jpg
title: Ville Johannes Pajala
description: The Blog
