typography_spectrum: 0.89287323015742
color:
  brandStrength: 0.6382027673535049
  lightness: 0.970947353169322
  saturation: 0.35477061686106026
  rhythmicContrast: 0.7133600788656622
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.826624329900369
author:
  name: Ville Johannes Pajala
  email: valoraami@gmail.com
  url: www.villepajala.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7fb35733-dd01-4516-b3d1-2eb57e5c2d1d.jpg
name: Ville Johannes Pajala
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/45db0fc3-633b-4efc-8cbe-229c40180eda.jpg
title: Ville Johannes Pajala
description: 'Memories, Dreams, Reflections'
