typography_spectrum: 0.008299479261040688
color:
  brandStrength: 0.465345069533214
  lightness: 0.938807274447754
  saturation: 0.6378710330463946
  rhythmicContrast: 0.9310331302694976
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.28119745408184826
author:
  name: Ville Johannes Pajala
  email: valoraami@gmail.com
  url: www.villepajala.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7fb35733-dd01-4516-b3d1-2eb57e5c2d1d.jpg
name: Ville Johannes Pajala
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/45db0fc3-633b-4efc-8cbe-229c40180eda.jpg
title: Ville Johannes Pajala
description: The Blog
