typography_spectrum: 0.5144700687378645
color:
  brandStrength: 0.9439579409081489
  lightness: 0.6405927615705878
  saturation: 0.9031043888535351
  rhythmicContrast: 0.9147278885357082
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.4871556975413114
author:
  name: Ville Johannes Pajala
  email: valoraami@gmail.com
  url: www.villepajala.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7fb35733-dd01-4516-b3d1-2eb57e5c2d1d.jpg
name: Ville Johannes Pajala
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/45db0fc3-633b-4efc-8cbe-229c40180eda.jpg
title: Ville Johannes Pajala
description: The Blog
